### ISSUE TITLE
Bug in WKT and WKBElement.copy() and serialization problem with eve_sqlalchemy

### ISSUE THREAD

**Issue by hectorcanto** [geoalchemy/geoalchemy2#198]
I'm using GeoAlchemy2 0.5.0 in an Eve 0.7.10 (microframework based on Flask) + SQL Alchemy 1.2.11 app.

When serializing my Point Geometry as defined below I get the next error:
`geo = Column(geoalchemy2.Geometry(geometry_type='POINT', srid=4326))`

> TypeError: Object of type Function is not JSON serializable

Debugging the application I've encountered a deep copy of the WKB object in eve_sqlalchemy that returns a function instead of a copy of the object. The copy is to avoid garbage collection of the object, as saids in the eve_sqlalchemy code. The said line is in the following link:

https://github.com/pyeve/eve-sqlalchemy/blob/0.7.0/eve_sqlalchemy/utils.py#L78

The copy method returns a sqlalchemy function (the Function in the TypeError above) instead of a copy of the object. I think there is a problem there in the implementation of WKB (and WKT too).

I believe this might be a bug on the elements. To reproduce it:

```python
from geoalchemy2 import WKTElement
a = WKTElement('POINT(5 45)', srid=4326)
a.copy()
# prompt: <sqlalchemy.sql.functions.Function at 0x7fd3e1693ac8; copy>
```
Anyway, using the debugger I replaced the "function" to a deep copy of the said element and I get another unexpected error which I didn't have the time to explore yet.

> NotImplementedError: Operator 'getitem' is not supported on this expression

So, solving the copy thing might not resolve the situation, so I will appreciate any workaround to tranform the WKB into something serializable.

**Comment by adrien-berchet** [comment]
Thanks for your report.

The first thing is that the `a.copy()` should raise an exception instead of returning a `sqlalchemy.sql.functions.Function` object with no meaning. This behavior is now fixed in the master branch, thanks for having spotted that.

The second thing is about the copy thing. Indeed there is no copy actual method for `WKTElment` or `WKBElement` objects but I am not sure that such method would be relevant, except in your very specific use case. Anyway it is not anticipated in a future release.

Anyway, I do not know `eve_sqlalchemy` so I do not understand why you need to copy the objects but maybe you could use `val = copy.copy(val)` or `val = copy.deepcopy(val)` directly in `eve_sqlalchemy` instead of `val = val.copy()` (here: https://github.com/pyeve/eve-sqlalchemy/blob/0.7.0/eve_sqlalchemy/utils.py#L78)?

**Comment by elemoine** [comment]
@adrien-berchet as I understand it `val.copy()` in eve is for the special case of an association proxy. So I am not even sure adding a `copy` method to our `_SpatialElement` class would make some sense.

**Comment by adrien-berchet** [comment]
Yes, that's what I meant, sorry if I was not clear.

I think we can close this issue.
