### ISSUE TITLE
disable auto wrapped st_AsEWKB

### ISSUE THREAD

**Issue by DeoLeung** [geoalchemy/geoalchemy2#251]
Hi, I found that using the library will wrapped `st_asewkb` automatically around some postgis function and geometry column, is there a way to disable it?

this causes some type mis-match since we need to compile it into raw sql and pass to other application.

**Comment by loicgasser** [comment]
Wrapping most likely happens here:
https://github.com/geoalchemy/geoalchemy2/blob/master/geoalchemy2/types.py#L148

Depending on what you want to do you can change the wrapping function by sub-classing `Geometry` (at your own risk):
https://github.com/geoalchemy/geoalchemy2/blob/master/geoalchemy2/types.py#L219
You just need to change the `as_binary` class attribute to whatever you need.

**Comment by adrien-berchet** [comment]
Hi
As @loicgasser said, if you want to change to behavior of the geometry you can define a custom geometry class with the preferred function to use. For example, if you want to use `ST_AsGeoJson` instead of the default `ST_AsEWKB` you can define the following class to override the `as_binary` static attribute:

```
class GeoJsonGeometry(Geometry):
    as_binary = 'ST_AsGeoJson'
```

But your use case seems very specific if you don't want to execute the query but just building it with geoalchemy2 and then executing it with another application. You can not just set the `as_binary` attribute to None or an empty string to achieve this, you have to override the `column_expression` method of your custom class. Here is an example that shows the two methods:

```
from geoalchemy2 import Geometry
from sqlalchemy import Table, Column, MetaData, Integer, create_engine, select, insert


class GeoJsonGeometry(Geometry):
    as_binary = 'ST_AsGeoJson'


class RawGeometry(Geometry):

    def column_expression(self, col):
        return col


engine = create_engine('postgresql://adrien@localhost/test_251')

conn = engine.connect()
metadata = MetaData()

conn.execute("CREATE EXTENSION IF NOT EXISTS postgis;")

the_table = Table(
    'the_table', metadata,
    Column('id', Integer, primary_key=True),
    Column('bin_geom', Geometry('LINESTRING', 4326)),
    Column('geojson_geom', GeoJsonGeometry('LINESTRING', 4326)),
    Column('raw_geom', RawGeometry('LINESTRING', 4326)),
)

the_table.drop(conn, checkfirst=True)
the_table.create(conn)

data = [
    {
        "id": 0,
        "bin_geom": "SRID=4326;LINESTRING (0 0, 1 0)",
        "geojson_geom": "SRID=4326;LINESTRING (0 0, 1 0)",
        "raw_geom": "SRID=4326;LINESTRING (0 0, 1 0)"
    },
    {
        "id": 1,
        "bin_geom": "SRID=4326;LINESTRING (0 1, 1 1, 1 2)",
        "geojson_geom": "SRID=4326;LINESTRING (0 1, 1 1, 1 2)",
        "raw_geom": "SRID=4326;LINESTRING (0 1, 1 1, 1 2)"
    }
]

query = insert(the_table).values(data)
conn.execute(query)

select_query = select([the_table])

print(select_query)

res = conn.execute(select_query).fetchall()
for i in res:
    print("id: {}\n\tbinary geom: {}\n\tGeoJson geom: {}\n\tRaw geom: {}".format(*i))
pass
```
 This code should produce the following output query:
```
SELECT the_table.id, ST_AsEWKB(the_table.bin_geom) AS bin_geom, ST_AsGeoJSON(the_table.geojson_geom) AS geojson_geom, the_table.raw_geom 
FROM the_table
```
As you can see, the `raw_geom` column is not wrapped by any function in the query. Is it what you need?

**Comment by felytic** [comment]
Hi!

There is the same issue with PostGIS functions without any column reference, for example:
```
>>> print(sa.select([sa.func.ST_MakePoint(1, 2)]))
SELECT ST_AsEWKB(ST_MakePoint(:ST_MakePoint_2, :ST_MakePoint_3)) AS "ST_MakePoint_1"
```
Is it possible to remove wrapping in this case?

**Comment by felytic** [comment]
Thanks a lot, @adrien-berchet!

**Comment by adrien-berchet** [comment]
You're welcome :)

**Comment by adrien-berchet** [comment]
Example added in doc (#260)
