### ISSUE TITLE
support for box data types?

### ISSUE THREAD

**Issue by StephenWithPH** [geoalchemy/geoalchemy2#295]
First, forgive my question if it misses something obvious.

It appears that geoalchemy2 does not support PostGIS's [box data types](https://postgis.net/docs/reference.html#PostGIS_Types). Is this something that is theoretically possible to add?

**Comment by adrien-berchet** [comment]
Hi @StephenWithPH 
I think it is possible to add it. You can try to copy the `Geometry` type and it should be quite close.
Nevertheless, you will have to tweak the IO because a Box2D, if I am correct, can not be exported and imported in an easy way. For example, I think you will have to override the `bind_expression` method with something like:
```python
    def bind_expression(self, bindvalue):
        return getattr(func, "Box2D")(getattr(func, "ST_GeomFromEWKT")(bindvalue), type_=self)
```

Please tell if it works as intended for your use case.

**Comment by StephenWithPH** [comment]
I'm closing this issue. I ended up running away from this problem.
