### ISSUE TITLE
Calculating geometry area in square meters

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [geoalchemy/geoalchemy2#305]
I had some trouble calculating the actual area of a geometry in square meters.
Finally i was able to achieve this using the internal `_ST_BestSRID()` function, but would like your opinions, if there is a better way to do this.

Short use case intro:
- database with Polygons that can be all over the world
- calcualtion of area during insertion from geojson.

Calling ST_Area on the geometry would just return me the area in degrees, which obviously doesn't help.
As we want to calculate the area in meters we need to reproject the geometry to meter based projection.
But we have to pass the projection dynamically because we don't know where the Polygon will be.

This is my current solution:
```py
from geoalchemy2 import func, Geometry

# db is an sqlalchemy Session object
        geom = func.ST_GeomFromGeoJSON(obj_in.geometry.json())
        area = calculate_geometry_area(db, geom)

def calculate_geometry_area(db: Session, geom: Geometry):
    # get the best Projection for area calculation
    best_area_projection = db.execute(func._ST_BestSRID(geom)).scalar()
    # reproject to
    transformed_geom = func.ST_Transform(geom, best_area_projection)
    # calculate polygon area
    area = db.execute(func.ST_Area(transformed_geom)).scalar()
    return round(area, 2)
```

I'm still a bit confused as to when i can call a function just through the `func` and when i have to execute it in the database and getting back an actual value with `.scalar()`. Any hints on that are very welcome :)

Feel free to close this whenever.

**Comment by adrien-berchet** [comment]
Hi

Considering your use case ("calculation of area during insertion from geojson"), I think you could use something similar to this: https://geoalchemy-2.readthedocs.io/en/latest/gallery/test_length_at_insert.html#sphx-glr-gallery-test-length-at-insert-py

For your actual issue with the SRID, you have polygons in lon-lat coordinates and you don't know the proper SRID to use for each of them, is it right? If this is the case, it is quite hard to answer to this part because the 'best' SRID obviously depends on the position of the polygon but it also depends on its size and even on what properties you want to be the closer to 'reality' (the angles, the lengths, ...). I am not an expert on this part though. Anyway, the `_BestSRID` function is very simple and should be used with caution.

**Comment by TheGreatRefrigerator** [comment]
Hi @adrien-berchet,

thank you for your answer.
For my usecase i only want to calculate the polygon area right now, so i would need an equal area projection for the region of the polygon (angles and lengths can therefore be incorrect). I thought `_ST_BestSRID()` is trying exactly that.

I could also just use a similar approach like [geojsonio](https://github.com/mapbox/geojson-area/blob/master/index.js) but i think that wouldn't be as accurate

**Comment by adrien-berchet** [comment]
Indeed, `_ST_BestSRID()` does what you need, you just have to keep in mind that it does it in a quite simple way and the result is not accurate. So it all depends on your needs.

**Comment by adrien-berchet** [comment]
Feel free to reopen if you need more help on this.
