### ISSUE TITLE
How can I use Geosqlalchemy to store TIFF images in a Postgres database?

### ISSUE THREAD

**Issue by mht2953658596** [geoalchemy/geoalchemy2#437]
Hello, I have been troubled by a problem for a long time and I hope to get your help.
I want to store tiff images into a database using Geosqlalchemy and save the image information as a Raster type so that I can perform spatial queries on the image. I do not want to use the raster2pgsql.py script.
Here is the code to create the table:

```
    class MyTable(Base):
        __tablename__ = 'my_table'
        id = Column(Integer, primary_key=True)
        year = Column(Integer)
        month = Column(Integer)
        name = Column(Text)
        type = Column(Text)
       rast = Column(Raster)
```

"id" represents the image number, "year" and "month" represent the time when the image was recorded, "type" represents the image type, and "rast" represents the raster information. It is worth mentioning that I want the result of storing "rast" to be the same as the output of the "raster2pgsql.py" script.

I am currently struggling with how to use the GDAL library to read a TIFF file and convert it to a HEX WKB format binary stream, and then store it using Geosqlalchemy.

Using the following code, I have made some initial progress, but I am unable to handle larger files such as a 1GB TIFF file very well

```
def bytes_from_gdal(ds):
    vsipath = '/vsimem/output.tif'
    gdal.GetDriverByName("GTiff").CreateCopy(vsipath, ds)
    # Read /vsimem/output.tif
    f = gdal.VSIFOpenL(vsipath, 'rb')
    gdal.VSIFSeekL(f, 0, 2) # seek to end
    size = gdal.VSIFTellL(f)
    gdal.VSIFSeekL(f, 0, 0) # seek to beginning
    data = gdal.VSIFReadL(1, size, f)
    gdal.VSIFCloseL(f)
    return data
```
```
def load_into_PostGIS(connection, image_name):
    ds = gdal.Open(image_name)

    with connection, connection.cursor() as cursor:
        # Create a table to store the raster data if it doesn't already exist
        cursor.execute("CREATE TABLE IF NOT EXISTS public.my_raster_table (id SERIAL PRIMARY KEY, rast RASTER)")

        # Convert the GDAL dataset object to a bytes object
        raster_data = bytes_from_gdal(ds)

        # Insert the raster data into the PostGIS database
        cursor.execute("INSERT INTO public.my_raster_table (rast) VALUES (ST_FromGDALRaster(%s))", (raster_data,))
```

But this method only works for TIFF images with small file sizes. For larger TIFF images, the generated vsipath temporary file will be very large. By very large, I mean that the program seems to not stop, and as the program runs for longer, the vsipath file will become increasingly larger, even reaching up to 80GB. So I wanted to ask if there's a better way to store TIFF images in PostgreSQL using Geosqlalchemy

I'm really at a loss and I hope to get your help. If you can help me, I would be very grateful.I am looking forward to your reply

**Comment by terrispacey** [comment]
Joining to the question. I have also spent the last whole days on finding a solution for a similar problem with no luck... 
I have a geotiff and I try to save it in a raster column. My input data was built using rasterio (arr is a numpy array):

```python
        with rasterio.io.MemoryFile() as memfile:
            with memfile.open(
                driver='GTiff',
                height=arr.shape[0],
                width=arr.shape[1],
                count=1,
                dtype=str(arr.dtype),
                crs=crs,
                transform=transform
            ) as dataset:
                dataset.write(arr, 1)
            result_geotiff = memfile.read()
``` 

The result_geotiff is [memoryview](https://docs.python.org/3/library/stdtypes.html#memoryview) object. When I first tried to use the Rater type in geoalchemy2, it didn't work because the input is not in WKB format. Long story short, I have decided to build new Raster type by myself. I encountered some issues in building it and opened (few hours ago) a discussion on the sqlalchemy github: [https://github.com/sqlalchemy/sqlalchemy/discussions/9584](https://github.com/sqlalchemy/sqlalchemy/discussions/9584). The answer there was to try and use geoalchemy2, but as I mentioned before, I could not use it in my case

**Comment by adrien-berchet** [comment]
Hi there.
Raster inserts are a bit boring indeed...
This issue was already discussed in #290, you can find some elements there (see my main answer: https://github.com/geoalchemy/geoalchemy2/issues/290#issuecomment-683421834).
The best solution would be to create a function that transforms an input (like a TIFF image or a numpy array) into a Raster WKB which can then be inserted easily. Basically we 'just' have to mimic what is done in the [raster2pgsql.py script](https://trac.osgeo.org/postgis/browser/trunk/raster/scripts/python/raster2pgsql.py), which if the inverse of the inverse of https://geoalchemy-2.readthedocs.io/en/latest/gallery/test_decipher_raster.html#sphx-glr-gallery-test-decipher-raster-py. If someone could propose a PR for this it would be great!

**Comment by terrispacey** [comment]
I finally found a solution. Instead of using ST_FromGDALRaster, which ignored my srid, I used ST_RastFromWKB. To use that function, I had to transform my rasterio dataset into a WKB raster. To do that, I used [nathancahill/wkb-raster](https://github.com/nathancahill/wkb-raster) project.

So, to prepare the data, I did:
```python
with rasterio.io.MemoryFile() as memfile:
    with memfile.open(
        driver='GTiff',
        height=prediction.shape[0],
        width=prediction.shape[1],
        count=1,
        dtype=str(prediction.dtype),
        nodata=0,
        crs=crs,
        transform=transform
    ) as dataset:
        dataset.write(prediction, 1)
        print(type(dataset))
        result_geotiff = write_wkb_raster(dataset)
``` 

And I built a new type:
```python
from sqlalchemy.types import UserDefinedType
from sqlalchemy import func

class Raster(UserDefinedType):
    def get_col_spec(self):
        return "RASTER"

    def bind_expression(self, bindvalue):
        return func.ST_RastFromWKB(bindvalue, type_=self)

    def column_expression(self, col):
        return func.ST_AsTiff(col, type_=self)
``` 

[nathancahill/wkb-raster](https://github.com/nathancahill/wkb-raster) has some bugs and I had to change it to work well. You need to change the pixtype to 11 (instead of 10) when dtype is float64. I changed it after looking at _PTYPE value in your example: [Decipher Raster](https://geoalchemy-2.readthedocs.io/en/latest/gallery/test_decipher_raster.html#sphx-glr-gallery-test-decipher-raster-py). It seems that _PTYPE skips key 9. I don't know why, but in the [official RFC](https://trac.osgeo.org/postgis/wiki/WKTRaster/RFC/RFC2_V0WKBFormat), I see all pixtype from 0 to 10 without 11.

**Comment by mht2953658596** [comment]
Hi [terrispacey](https://github.com/terrispacey)

> I finally found a solution. Instead of using ST_FromGDALRaster, which ignored my srid, I used ST_RastFromWKB. To use that function, I had to transform my rasterio dataset into a WKB raster. To do that, I used [nathancahill/wkb-raster](https://github.com/nathancahill/wkb-raster) project.

I have followed your suggestion to use [nathancahill/wkb-raster](https://github.com/nathancahill/wkb-raster) project，but i failed .The specific reasons are as follows: 
First, the person in charge of this project did not update the project on PYPI. This project has reached version 0.7 on github, but it is still 0.6 on PYPI， According to，https://github.com/nathancahill/wkb-raster/issues/6#:~:text=Release%20new%20version%200.7%20on%20PyPI%20%236

Second，The update of this project is not big, the new version only adds a function named "write_wkb_raster", I manually update this library, but my ability is not very good, I can't fix the bug in this function like you, so I Hope to get your help, tell me how to modify


Then，I get a solution from https://github.com/geoalchemy/geoalchemy2/issues/290：

```
class GDALRaster(Raster):
    def bind_expression(self, bindvalue):
        return ST_FromGDALRaster(bindvalue)
    
class Image(Base):
    __tablename__ = 'images'
    id = Column(Integer, primary_key=True)
    image = Column(GDALRaster)

Base.metadata.create_all(engine)


tiff_file = r"/atest.tif"
with open(tiff_file, 'rb') as f:
    bytea_data = f.read()


image = Image(id=1999, image=bytea_data)
session.add(image)

```
I use the subclass of the Raster,But  I also encounter with the trouble：when i upload a big tiff,there is an error:(psycopg2.OperationalError) cannot allocate memory for output buffer


Dear [terrispacey](https://github.com/terrispacey) ,I need you tell me how to fix the bug in  [nathancahill/wkb-raster](https://github.com/nathancahill/wkb-raster)
Thanks

**Comment by terrispacey** [comment]
Hi @mht2953658596,
You right, I used the code from the master branch.
In order to fix that, first replace row 382 with:
```python
nodata = pack(fmt, int(dataset.meta.get("nodata") or 0))
``` 
This allows None for nodata (this is helpful when you save the rasterio dataset without specifying what is nodata).

Then, replace rows 364-365 with this:
```python
psize = 11 if pixtype == 10 else pixtype
# format binary -> :b
binary_str = f"{isOffline:b}{hasNodataValue:b}{isNodataValue:b}{reserved:b}{psize:b}"
``` 
This fixes the pixtype issue. Maybe it will be better to write it differently and more readable, but for my case it was enough.

**Comment by terrispacey** [comment]
> > I finally found a solution. Instead of using ST_FromGDALRaster, which ignored my srid, I used ST_RastFromWKB. To use that function, I had to transform my rasterio dataset into a WKB raster. To do that, I used [nathancahill/wkb-raster](https://github.com/nathancahill/wkb-raster) project.
> 
> Nice! 🤩 This solution looks very good. I think we should add this solution in the gallery of GeoAlchemy2. I will try to do it later.
That's sounds great! Thanks!
> 
> > [nathancahill/wkb-raster](https://github.com/nathancahill/wkb-raster) has some bugs and I had to change it to work well. You need to change the pixtype to 11 (instead of 10) when dtype is float64. I changed it after looking at _PTYPE value in your example: [Decipher Raster](https://geoalchemy-2.readthedocs.io/en/latest/gallery/test_decipher_raster.html#sphx-glr-gallery-test-decipher-raster-py). It seems that _PTYPE skips key 9. I don't know why, but in the [official RFC](https://trac.osgeo.org/postgis/wiki/WKTRaster/RFC/RFC2_V0WKBFormat), I see all pixtype from 0 to 10 without 11.
> 
> The internal documentation (https://trac.osgeo.org/postgis/browser/trunk/raster/doc/RFC2-WellKnownBinaryFormat) uses pixtype values up to 11 and skips the value 9, so I guess, the other link you posted (https://trac.osgeo.org/postgis/wiki/WKTRaster/RFC/RFC2_V0WKBFormat) is not up to date. Or maybe OSGEO does not follow the official spec, I don't know.
You right. It is not up-to-date. They changed 5 years ago: [https://trac.osgeo.org/postgis/changeset/16452/trunk/raster/doc/RFC2-WellKnownBinaryFormat](https://trac.osgeo.org/postgis/changeset/16452/trunk/raster/doc/RFC2-WellKnownBinaryFormat)

**Comment by adrien-berchet** [comment]
I opened a new PR to add an example based on the solution of @terrispacey here: #438 
If you can review it to check it is correct and clear it would be nice :)

**Comment by amit-hazan** [comment]
This looks great! I'll test it in the next days and give my feedback.
Meanwhile, I'll appreciate if you could fix the @mention username in your comment 😊

**Comment by mht2953658596** [comment]
there is an error in https://github.com/geoalchemy/geoalchemy2/pull/438

**Comment by adrien-berchet** [comment]
> there is an error in #438

Maybe :)
Could you elaborate a bit please? What is the error?

**Comment by mht2953658596** [comment]
after i check you are right ,there is no error

**Comment by adrien-berchet** [comment]
> after i check you are right ,there is no error

Perect, thanks for your check!

**Comment by RickLeite** [comment]
@adrien-berchet Can you do a Tutorial?
I am trying on esri land use tiff files, and it is returning me `error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)` when calling write_wkb_raster function

**Comment by adrien-berchet** [comment]
Hi @RickLeite !
Isn't it just because the values in your dataset are too big to be stored properly in the associated type? Is it possible that the type of your dataset is not correct? Or maybe there is something wrong in the function, I'm not sure all types are properly handled...
Could you provide a complete example that reproduces your issue and the TIFF file you use? (or a small portion of it if it's too big)

**Comment by RickLeite** [comment]
> Hi @RickLeite ! Isn't it just because the values in your dataset are too big to be stored properly in the associated type? Is it possible that the type of your dataset is not correct? Or maybe there is something wrong in the function, I'm not sure all types are properly handled... Could you provide a complete example that reproduces your issue and the TIFF file you use? (or a small portion of it if it's too big)

@adrien-berchet  Correct me if I'm wrong, I just need to do the following?

```
file_path = "/dbfs/FileStore/ESRI_LandUse/24M_20220101-20230101.tif"
dataset = rasterio.open(file_path)
wkb = write_wkb_raster(dataset)
```


```
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
File <command-916277992952930>:1
----> 1 wkb = write_wkb_raster(dataset)

File <command-916277992953166>:40, in write_wkb_raster(dataset)
     36 height = int(dataset.meta.get("height"))
     38 fmt = f"{endian}{format_string}"
---> 40 header = struct.pack(
     41     fmt,
     42     endian_byte,
     43     version,
     44     nBands,
     45     scaleX,
     46     scaleY,
     47     ipX,
     48     ipY,
     49     skewX,
     50     skewY,
     51     srid,
     52     width,
     53     height,
     54 )
     56 bands = []
     58 # Create band header data
     59 
     60 # not used - always False

error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)
```

I think that the file isn't too big, around 140MB, but I will be handling various other files like this one, and my final data would reach at least 3GB.

**Comment by adrien-berchet** [comment]
As far as I remember, here is the complete process:
```python
with rasterio.open(str(filename), "r+") as dataset:
    dataset.crs = rasterio.crs.CRS.from_epsg(4326)  # Or any other SRID
    raw_wkb = write_wkb_raster(dataset)
element = RasterElement(raw_wkb)
# Then use the element in a query
```

For your issue, what is the size of your raster (along X and Y)? I'm wondering if the width or height is not too big to be stored in a `uint16`?

**Comment by RickLeite** [comment]
Some informations that I get:

1. **Raster dimensions:**
   - Width: 66794
   - Height: 88550
   
    5914608700 pixels

2. **Pixel size:**
   - X dimension (pxsz): 10.0
   - Y dimension (pysz): 10.0

3.  **Affine transformation matrix:**
Affine(10.0, 0.0, 166030.0,
0.0, -10.0, 10000000.0)

**Comment by adrien-berchet** [comment]
Ok, so your raster is too big (PostGIS only supports rasters with height and width both smaller than 65535), you have to divide it into smaller tiles. You could use the `raster2pgsql` script if it is relevant in your workflow or create the tiles with another tool or even manually.

**Comment by adrien-berchet** [comment]
To be more clear I updated the example in the gallery: #482

**Comment by RickLeite** [comment]
> To be more clear I updated the example in the gallery: #482

Thanks!
